name: firmware.docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'firmware/**'
    - '.config/**'
    - '.github/**'

jobs:
  Docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # GET DEPENDENCIES
    - name: Install dependencies
      run: sudo apt-get install -y doxygen
    - run: doxygen --version

    # BUILD
    - name: Build docs
      run: |
        cd firmware
        mkdir -p docs/xml docs/md
        doxygen Doxyfile
        npx moxygen --templates=docs/templates --groups --classes --output=docs/md/%s.md docs/xml
        #cp ./README.md ./firmware/docs/md/index.md

    # UPLOAD
    - name: Upload Docs
      uses: actions/upload-artifact@v2.1.3
      with:
        name: Docs
        path: firmware/docs
        
#  Publish:
#    runs-on: ubuntu-latest
#    continue-on-error: true
#    needs: Docs
#    steps:
#    - uses: actions/checkout@v2
#
#    # DOWNLOAD ARTIFACT
#    - name: Download Docs
#      uses: actions/download-artifact@v2.0.4
#      with:
#        name: Docs

    # PUBLISH
    - name: Publish Firmware Docs
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./firmware/docs/md
        enable_jekyll: true
        force_orphan: true
        keep_files: true
        destination_dir: ./
