name: hardware.docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'hardware/**'
    - '.config/**'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'hardware/**'
    - '.config/**'
    - '.github/**'

jobs:
  Schematics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # RUN
    - name: kicad-exports schematics
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/schematics.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch

    # CHECK
    - name: "check output: schematics"
      run: |
        test -f hardware/docs/MCB19-Schematic*.svg && \
        test -f hardware/docs/MCB19-Schematic*.pdf && \
        test -f hardware/docs/MCB19-Board*.pdf
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: docs
        path: hardware/docs/*

    # PUBLISH
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./hardware/docs
        enable_jekyll: true
        keep_files: true
        destination_dir: ./

  Bom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    # RUN
    - name: kicad-exports bom
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/bom.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch

    # CHECK
    - name: "check output: bom"
      run: |
        test -f hardware/docs/bom/MCB19*.html && \
        test -f hardware/docs/bom/MCB19*.csv && \
        test -f hardware/docs/bom/MCB19*.xlsx
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: bom
        path: hardware/docs/bom/*

    # PUBLISH
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./hardware/docs/bom
        enable_jekyll: true
        keep_files: true
        destination_dir: ./

  Plot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # RUN
    - name: kicad-exports plot
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/plot.kiplot.yaml
        dir: hardware
        schema: hardware/MCB19.sch
        board: hardware/MCB19.kicad_pcb

    # CHECK
    - name: "check output: plot"
      run: |
        test -f hardware/docs/img/MCB19-top.svg && \
        test -f hardware/docs/img/MCB19-bottom.svg 
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: img
        path: hardware/docs/img/*

    # PUBLISH
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./hardware/docs
        enable_jekyll: true
        keep_files: true
        destination_dir: ./

  Model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # RUN
    - name: kicad-exports model
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/model.kiplot.yaml
        dir: hardware
        schema: hardware/MCB19.sch
        board: hardware/MCB19.kicad_pcb

    # CHECK
    - name: "check output: model"
      run: |
        ls hardware/docs/cad #debug
        test -f hardware/docs/cad/MCB19.step && \
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: cad
        path: hardware/docs/cad/*

    # PUBLISH
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./hardware/docs/cad
        enable_jekyll: true
        keep_files: true
        destination_dir: ./

