name: HARDWARE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports docs
      uses: nerdyscout/kicad-exports@develop
      with:
        config: docs.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch
    - name: "check output: docs"
      run: |
        test -f hardware/docs/MCB19-Schematic*.svg && \
        test -f hardware/docs/MCB19-Schematic*.pdf && \
        test -f hardware/docs/MCB19-Board*.pdf
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: docs
        path: hardware/docs/*

  Bom:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports bom
      uses: nerdyscout/kicad-exports@develop
      with:
        config: bom.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch
    - name: "check output: bom"
      run: |
        test -f hardware/docs/bom/MCB19*.html && \
        test -f hardware/docs/bom/MCB19*.csv && \
        test -f hardware/docs/bom/MCB19*.xlsx
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: bom
        path: hardware/docs/bom/*

  Fabrications:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports fabrications 
      uses: nerdyscout/kicad-exports@develop
      with:
        config: fabrications.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch
    - name: "check output: fabrications"
      run: |
        test -f hardware/gerbers/*B_CrtYd.gbr && \
        test -f hardware/gerbers/*F_CrtYd.gbr && \
        test -f hardware/gerbers/*B_Cu.gbr && \
        test -f hardware/gerbers/*F_Cu.gbr && \
        test -f hardware/gerbers/*B_Mask.gbr && \
        test -f hardware/gerbers/*F_Mask.gbr && \
        test -f hardware/gerbers/*B_Paste.gbr && \
        test -f hardware/gerbers/*F_Paste.gbr && \
        test -f hardware/gerbers/*B_SilkS.gbr && \
        test -f hardware/gerbers/*F_SilkS.gbr && \
        test -f hardware/gerbers/*B_CrtYd.gbr && \
        test -f hardware/gerbers/*F_CrtYd.gbr && \
        test -f hardware/gerbers/*NPTH*.gbr && \
        test -f hardware/gerbers/*NPTH*.drl && \
        test -f hardware/gerbers/*-PTH*.gbr && \
        test -f hardware/gerbers/*-PTH*.drl && \
        test -f hardware/gerbers/*_pos.csv
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: gerbers
        path: hardware/gerbers/*, hardware/*.rpt

  Plot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports plot
      uses: nerdyscout/kicad-exports@develop
      with:
        config: plot.kiplot.yaml
        dir: hardware
        schema: hardware/MCB19.sch
        board: hardware/MCB19.kicad_pcb
    - name: "check output: plot"
      run: |
        test -f hardware/docs/img/MCB19-top.svg && \
        test -f hardware/docs/img/MCB19-bottom.svg 
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: img
        path: hardware/docs/img/*
