name: hardware.fabrication

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'hardware/**'
    - '.config/**'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'hardware/**'
    - '.config/**'
    - '.github/**'

jobs:
  Bom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # RUN
    - name: kicad-exports bom
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/bom.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch

    # CHECK
    - name: "check output: bom"
      run: |
        test -f hardware/docs/bom/MCB19*.html && \
        test -f hardware/docs/bom/MCB19*.csv && \
        test -f hardware/docs/bom/MCB19*.xlsx
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: bom
        path: hardware/docs/bom/*
        
    # UPLOAD
    - name: Upload Bom
      uses: actions/upload-artifact@v2.1.3
      with:
        name: Bom
        path: hardware/bom

  Fabrications:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # RUN
    - name: kicad-exports fabrications 
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/fabrications.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch

    # CHECK
    - name: "check output: fabrications"
      run: |
        test -f hardware/gerbers/*B_CrtYd.gbr && \
        test -f hardware/gerbers/*F_CrtYd.gbr && \
        test -f hardware/gerbers/*B_Cu.gbr && \
        test -f hardware/gerbers/*F_Cu.gbr && \
        test -f hardware/gerbers/*B_Mask.gbr && \
        test -f hardware/gerbers/*F_Mask.gbr && \
        test -f hardware/gerbers/*B_Paste.gbr && \
        test -f hardware/gerbers/*F_Paste.gbr && \
        test -f hardware/gerbers/*B_SilkS.gbr && \
        test -f hardware/gerbers/*F_SilkS.gbr && \
        test -f hardware/gerbers/*B_CrtYd.gbr && \
        test -f hardware/gerbers/*F_CrtYd.gbr && \
        test -f hardware/gerbers/*NPTH*.gbr && \
        test -f hardware/gerbers/*NPTH*.drl && \
        test -f hardware/gerbers/*-PTH*.gbr && \
        test -f hardware/gerbers/*-PTH*.drl && \
        test -f hardware/gerbers/*_pos.csv
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: gerbers
        path: hardware/gerbers/*, hardware/*.rpt
        
    # UPLOAD
    - name: Upload Fabrications
      uses: actions/upload-artifact@v2.1.1
      with:
        name: Fabrications
        path: hardware/gerbers
