name: hardware.check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'hardware/**'
    - '.config/**'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'hardware/**'
    - '.config/**'
    - '.github/**'

jobs:
  ERC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # RUN
    - name: kicad-exports erc
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/erc.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch

  DRC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # RUN
    - name: kicad-exports drc
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: ./.config/drc.kiplot.yaml
        dir: hardware
        board: hardware/MCB19.kicad_pcb
        schema: hardware/MCB19.sch
