# This is a basic workflow to help you get started with Actions

name: BUILD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    
    # GET DEPENDENCIES
    - name: Install dependencies
      run: sudo apt-get install -y binutils-avr gcc-avr avr-libc doxygen
    - run: avr-gcc --version
      
    # BUILD
    - name: Build libraries
      run: |
        cd firmware
        ./makelibs.sh
      
    - name: Build firmware
      run: |
        cd firmware
        make

    - name: Upload firmware
      uses: actions/upload-artifact@v2.1.1
      with:
        name: Firmware
        path: firmware/bin

    - name: Build docs
      run: |
        cd firmware
        mkdir -p docs/xml docs/md
        doxygen Doxyfile
        npx moxygen --groups --classes --output=docs/md/%s.md docs/xml
        
    - name: Publish Docs
      uses: peaceiris/actions-gh-pages@v3.6.4
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: firmware/docs/md
        force_orphan: true
        enable_jekyll: true
        #keep_files: true
        #allow_empty_commit: true
